name: cloud_spa
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3
  sms_autofill: ^2.0.0
  intl_phone_number_input: ^0.7.0+2
  url_launcher: ^5.4.0
  image_picker: ^0.8.0+1
  shared_preferences: 2.0.6
  smooth_star_rating: 1.0.3
  dio: ^4.0.0
  json_annotation: ^4.0.1
  lottie: ^0.7.0+1
  rxdart: ^0.27.1
  flutter_swiper: ^1.1.6

  # meta: ^1.2.4
  curved_navigation_bar:
    #    path: ../curved_navigation_bar/
    git:
        url: https://github.com/Akhileshsuvarna/curved_navigation_bar.git
  curved_navigation_bar_custom:
    git:
      url: https://github.com/PannagaShetty/curved_navigation_bar.git
  file_picker: ^3.0.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/auth_svg/
    - assets/svg/registration/
    - assets/svg/home/
    - assets/svg/user_home/
    - assets/images/
    - assets/anim/

  fonts:
    - family: SfUiDisplay
      fonts:
        - asset: assets/font/sf_ui_display.otf

    - family: SfUiDisplayLight
      fonts:
        - asset: assets/font/sf-ui-display-thin.otf